'use client';

/**
 * Iron Coach Planner — Weekly Plan Viewer
 * 
 * Displays a personalized weekly fitness and nutrition plan
 * generated by Iron Coach AI. Read-only - users cannot write messages.
 */

import React, { useState, useEffect, useCallback, useMemo } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { 
  Calendar, Dumbbell, Utensils, Moon, Pill, Bell, 
  ChevronLeft, ChevronRight, RefreshCw, Sparkles, 
  Loader2, Target, Zap, Clock, CheckCircle2
} from 'lucide-react';
import { cn } from '@/lib/utils';
import { apiFetch } from '@/lib/mobile-api';

// ═══════════════════════════════════════════════════════════════
// Types
// ═══════════════════════════════════════════════════════════════

interface FoodItem {
  food_name: string;
  quantity: number;
  unit: string;
  calories: number;
  protein: number;
  carbs: number;
  fat: number;
}

interface Meal {
  meal_type: 'breakfast' | 'lunch' | 'dinner' | 'snack';
  foods: FoodItem[];
  notes?: string;
}

interface Workout {
  exercise_name: string;
  type: string;
  sets: number;
  reps: number;
  weight: number;
  calories_burned: number;
  intensity: 'low' | 'moderate' | 'high';
  notes?: string;
}

interface SleepData {
  bedtime: string;
  wake_time: string;
  recommended_duration_minutes: number;
  notes?: string;
}

interface Supplement {
  supplement_name: string;
  quantity: number;
  unit: string;
  time_of_day: string;
}

interface DailyPlan {
  date: string;
  day_name: string;
  workout: Workout[];
  nutrition: {
    total_calories: number;
    total_protein: number;
    total_carbs: number;
    total_fat: number;
    meals: Meal[];
  };
  sleep: SleepData;
  supplements: Supplement[];
  daily_reminders: string[];
  coach_message: string;
  confidence: number;
}

interface WeeklyPlan {
  week_start: string;
  week_end: string;
  daily_plan: DailyPlan[];
  overall_confidence: number;
  week_summary: string;
}

interface IronCoachPlannerProps {
  theme?: string;
  onClose?: () => void;
}

// ═══════════════════════════════════════════════════════════════
// Theme Styles
// ═══════════════════════════════════════════════════════════════

function getThemeStyles(theme: string) {
  switch (theme) {
    case 'gymbro':
      return {
        container: 'bg-[#050607]',
        card: 'bg-[#0A0C0E] border-red-900/30',
        header: 'text-white',
        subtext: 'text-zinc-400',
        accent: 'text-red-400',
        accentBg: 'bg-red-500/20',
        border: 'border-red-900/30',
        button: 'bg-red-500 hover:bg-red-600',
        badge: 'bg-red-500/20 text-red-400',
      };
    case 'gymgirl':
      return {
        container: 'bg-[#FFE4EE]',
        card: 'bg-white/90 border-pink-200',
        header: 'text-[#4A1A2C]',
        subtext: 'text-pink-400',
        accent: 'text-pink-500',
        accentBg: 'bg-pink-100',
        border: 'border-pink-200',
        button: 'bg-pink-500 hover:bg-pink-600',
        badge: 'bg-pink-100 text-pink-600',
      };
    default:
      return {
        container: 'bg-zinc-900',
        card: 'bg-zinc-800 border-zinc-700',
        header: 'text-white',
        subtext: 'text-zinc-400',
        accent: 'text-orange-400',
        accentBg: 'bg-orange-500/20',
        border: 'border-zinc-700',
        button: 'bg-orange-500 hover:bg-orange-600',
        badge: 'bg-orange-500/20 text-orange-400',
      };
  }
}

// ═══════════════════════════════════════════════════════════════
// Day Card Component
// ═══════════════════════════════════════════════════════════════

function DayCard({ 
  day, 
  isActive, 
  onClick,
  styles 
}: { 
  day: DailyPlan; 
  isActive: boolean;
  onClick: () => void;
  styles: ReturnType<typeof getThemeStyles>;
}) {
  const today = new Date().toISOString().split('T')[0];
  const isToday = day.date === today;
  const hasWorkout = day.workout.length > 0;
  
  return (
    <button
      onClick={onClick}
      className={cn(
        "w-full p-3 rounded-xl border text-left transition-all",
        styles.card,
        isActive && "ring-2 ring-orange-500",
        isToday && "border-l-4 border-l-orange-500"
      )}
    >
      <div className="flex items-center justify-between mb-2">
        <span className={cn("font-semibold", styles.header)}>{day.day_name}</span>
        {hasWorkout && <Dumbbell className={cn("w-4 h-4", styles.accent)} />}
      </div>
      <div className={cn("text-xs", styles.subtext)}>
        {new Date(day.date).toLocaleDateString('en-US', { month: 'short', day: 'numeric' })}
      </div>
      <div className="flex gap-2 mt-2 text-xs">
        <span className={cn("px-2 py-0.5 rounded-full", styles.badge)}>
          {day.nutrition.total_calories} cal
        </span>
        {hasWorkout && (
          <span className={cn("px-2 py-0.5 rounded-full", styles.badge)}>
            {day.workout.length} exercises
          </span>
        )}
      </div>
    </button>
  );
}

// ═══════════════════════════════════════════════════════════════
// Workout Section
// ═══════════════════════════════════════════════════════════════

function WorkoutSection({ workout, styles }: { workout: Workout[]; styles: ReturnType<typeof getThemeStyles> }) {
  if (!workout.length) {
    return (
      <div className={cn("p-4 rounded-xl border", styles.card, styles.border)}>
        <div className="flex items-center gap-2 mb-2">
          <Dumbbell className={cn("w-5 h-5", styles.accent)} />
          <span className={cn("font-semibold", styles.header)}>Workout</span>
        </div>
        <p className={cn("text-sm", styles.subtext)}>Rest Day 💀 Recover like a champion!</p>
      </div>
    );
  }

  const totalCalories = workout.reduce((sum, w) => sum + (w.calories_burned || 0), 0);

  return (
    <div className={cn("p-4 rounded-xl border", styles.card, styles.border)}>
      <div className="flex items-center justify-between mb-3">
        <div className="flex items-center gap-2">
          <Dumbbell className={cn("w-5 h-5", styles.accent)} />
          <span className={cn("font-semibold", styles.header)}>Workout</span>
        </div>
        <span className={cn("text-sm px-2 py-1 rounded-full", styles.badge)}>
          ~{totalCalories} cal burned
        </span>
      </div>
      
      <div className="space-y-2">
        {workout.map((exercise, i) => (
          <div key={i} className={cn("p-3 rounded-lg border", styles.border)}>
            <div className="flex items-center justify-between mb-1">
              <span className={cn("font-medium text-sm", styles.header)}>{exercise.exercise_name}</span>
              <span className={cn("text-xs px-2 py-0.5 rounded-full capitalize", styles.badge)}>
                {exercise.intensity}
              </span>
            </div>
            <div className={cn("text-xs", styles.subtext)}>
              {exercise.sets} sets × {exercise.reps} reps
              {exercise.weight > 0 && ` @ ${exercise.weight}kg`}
            </div>
            {exercise.notes && (
              <div className={cn("text-xs mt-1 italic", styles.subtext)}>{exercise.notes}</div>
            )}
          </div>
        ))}
      </div>
    </div>
  );
}

// ═══════════════════════════════════════════════════════════════
// Nutrition Section
// ═══════════════════════════════════════════════════════════════

function NutritionSection({ nutrition, styles }: { nutrition: DailyPlan['nutrition']; styles: ReturnType<typeof getThemeStyles> }) {
  const macroColors = {
    protein: 'text-red-400 bg-red-500/20',
    carbs: 'text-yellow-400 bg-yellow-500/20',
    fat: 'text-blue-400 bg-blue-500/20',
  };

  return (
    <div className={cn("p-4 rounded-xl border", styles.card, styles.border)}>
      <div className="flex items-center justify-between mb-3">
        <div className="flex items-center gap-2">
          <Utensils className={cn("w-5 h-5", styles.accent)} />
          <span className={cn("font-semibold", styles.header)}>Nutrition</span>
        </div>
        <span className={cn("text-sm font-bold", styles.accent)}>
          {nutrition.total_calories} cal
        </span>
      </div>

      {/* Macros Bar */}
      <div className="flex gap-2 mb-4">
        <div className={cn("flex-1 text-center p-2 rounded-lg", macroColors.protein)}>
          <div className="text-lg font-bold">{nutrition.total_protein}g</div>
          <div className="text-xs">Protein</div>
        </div>
        <div className={cn("flex-1 text-center p-2 rounded-lg", macroColors.carbs)}>
          <div className="text-lg font-bold">{nutrition.total_carbs}g</div>
          <div className="text-xs">Carbs</div>
        </div>
        <div className={cn("flex-1 text-center p-2 rounded-lg", macroColors.fat)}>
          <div className="text-lg font-bold">{nutrition.total_fat}g</div>
          <div className="text-xs">Fat</div>
        </div>
      </div>

      {/* Meals */}
      <div className="space-y-2">
        {nutrition.meals.map((meal, i) => (
          <div key={i} className={cn("p-3 rounded-lg border", styles.border)}>
            <div className={cn("text-xs font-semibold uppercase mb-2", styles.accent)}>
              {meal.meal_type}
            </div>
            <div className="space-y-1">
              {meal.foods.map((food, j) => (
                <div key={j} className="flex items-center justify-between text-sm">
                  <span className={styles.header}>{food.quantity}{food.unit} {food.food_name}</span>
                  <span className={cn("text-xs", styles.subtext)}>{food.calories} cal</span>
                </div>
              ))}
            </div>
            {meal.notes && (
              <div className={cn("text-xs mt-2 italic", styles.subtext)}>{meal.notes}</div>
            )}
          </div>
        ))}
      </div>
    </div>
  );
}

// ═══════════════════════════════════════════════════════════════
// Sleep & Supplements Section
// ═══════════════════════════════════════════════════════════════

function SleepSupplementsSection({ 
  sleep, 
  supplements, 
  reminders,
  styles 
}: { 
  sleep: SleepData; 
  supplements: Supplement[];
  reminders: string[];
  styles: ReturnType<typeof getThemeStyles>;
}) {
  return (
    <div className="grid grid-cols-2 gap-3">
      {/* Sleep */}
      <div className={cn("p-3 rounded-xl border", styles.card, styles.border)}>
        <div className="flex items-center gap-2 mb-2">
          <Moon className={cn("w-4 h-4", styles.accent)} />
          <span className={cn("font-semibold text-sm", styles.header)}>Sleep</span>
        </div>
        <div className={cn("text-lg font-bold", styles.header)}>
          {sleep.bedtime} → {sleep.wake_time}
        </div>
        <div className={cn("text-xs", styles.subtext)}>
          {Math.round(sleep.recommended_duration_minutes / 60)}h recommended
        </div>
      </div>

      {/* Supplements */}
      <div className={cn("p-3 rounded-xl border", styles.card, styles.border)}>
        <div className="flex items-center gap-2 mb-2">
          <Pill className={cn("w-4 h-4", styles.accent)} />
          <span className={cn("font-semibold text-sm", styles.header)}>Supplements</span>
        </div>
        {supplements.length > 0 ? (
          <div className="space-y-1">
            {supplements.slice(0, 3).map((s, i) => (
              <div key={i} className={cn("text-xs", styles.subtext)}>
                {s.supplement_name} {s.quantity}{s.unit}
              </div>
            ))}
          </div>
        ) : (
          <div className={cn("text-xs", styles.subtext)}>None planned</div>
        )}
      </div>

      {/* Reminders */}
      {reminders.length > 0 && (
        <div className={cn("col-span-2 p-3 rounded-xl border", styles.card, styles.border)}>
          <div className="flex items-center gap-2 mb-2">
            <Bell className={cn("w-4 h-4", styles.accent)} />
            <span className={cn("font-semibold text-sm", styles.header)}>Daily Reminders</span>
          </div>
          <div className="flex flex-wrap gap-2">
            {reminders.map((r, i) => (
              <span key={i} className={cn("text-xs px-2 py-1 rounded-full", styles.badge)}>
                {r}
              </span>
            ))}
          </div>
        </div>
      )}
    </div>
  );
}

// ═══════════════════════════════════════════════════════════════
// Main Component
// ═══════════════════════════════════════════════════════════════

export function IronCoachPlanner({ theme = 'dark' }: IronCoachPlannerProps) {
  const styles = useMemo(() => getThemeStyles(theme), [theme]);
  
  const [plan, setPlan] = useState<WeeklyPlan | null>(null);
  const [isLoading, setIsLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [selectedDayIndex, setSelectedDayIndex] = useState(0);

  // Load plan on mount
  const loadPlan = useCallback(async () => {
    setIsLoading(true);
    setError(null);
    
    try {
      const response = await apiFetch('/api/iron-coach/planner', {
        method: 'POST',
        body: JSON.stringify({ goal: 'general fitness improvement' }),
      });

      if (!response.ok) {
        throw new Error('Failed to generate plan');
      }

      const data = await response.json();
      
      if (data.success && data.plan) {
        setPlan(data.plan);
        
        // Find today's index
        const today = new Date().toISOString().split('T')[0];
        const todayIndex = data.plan.daily_plan.findIndex((d: DailyPlan) => d.date === today);
        if (todayIndex >= 0) {
          setSelectedDayIndex(todayIndex);
        }
      } else {
        throw new Error(data.message || 'Failed to generate plan');
      }
    } catch (err) {
      console.error('[IronCoachPlanner] Error:', err);
      setError(err instanceof Error ? err.message : 'Failed to load plan');
    } finally {
      setIsLoading(false);
    }
  }, []);

  useEffect(() => {
    loadPlan();
  }, [loadPlan]);

  // Get current day
  const currentDay = plan?.daily_plan[selectedDayIndex];

  // Loading state
  if (isLoading) {
    return (
      <div className={cn("flex flex-col items-center justify-center h-full p-8", styles.container)}>
        <Sparkles className={cn("w-12 h-12 mb-4 animate-pulse", styles.accent)} />
        <Loader2 className={cn("w-8 h-8 animate-spin mb-4", styles.accent)} />
        <div className={cn("text-lg font-semibold", styles.header)}>Iron Coach is building your plan...</div>
        <div className={cn("text-sm", styles.subtext)}>Analyzing your data and crafting the perfect week</div>
      </div>
    );
  }

  // Error state
  if (error || !plan) {
    return (
      <div className={cn("flex flex-col items-center justify-center h-full p-8", styles.container)}>
        <div className={cn("text-4xl mb-4")}>💀</div>
        <div className={cn("text-lg font-semibold mb-2", styles.header)}>Plan Generation Failed</div>
        <div className={cn("text-sm mb-4 text-center", styles.subtext)}>
          {error || "Something went wrong. Try again!"}
        </div>
        <button
          onClick={loadPlan}
          className={cn("px-4 py-2 rounded-lg text-white font-medium flex items-center gap-2", styles.button)}
        >
          <RefreshCw className="w-4 h-4" />
          Try Again
        </button>
      </div>
    );
  }

  return (
    <div className={cn("flex flex-col h-full", styles.container)}>
      {/* Header */}
      <div className={cn("p-4 border-b", styles.border)}>
        <div className="flex items-center justify-between mb-2">
          <div className="flex items-center gap-2">
            <Sparkles className={cn("w-6 h-6", styles.accent)} />
            <span className={cn("text-lg font-bold", styles.header)}>Weekly Plan</span>
          </div>
          <button
            onClick={loadPlan}
            className={cn("p-2 rounded-lg transition-colors", styles.accentBg)}
            title="Regenerate Plan"
          >
            <RefreshCw className={cn("w-4 h-4", styles.accent)} />
          </button>
        </div>
        <div className={cn("text-sm", styles.subtext)}>
          {new Date(plan.week_start).toLocaleDateString('en-US', { month: 'short', day: 'numeric' })} - {new Date(plan.week_end).toLocaleDateString('en-US', { month: 'short', day: 'numeric' })}
        </div>
        
        {/* Confidence Score */}
        <div className="flex items-center gap-2 mt-2">
          <div className="flex-1 h-2 bg-zinc-700 rounded-full overflow-hidden">
            <div 
              className={cn("h-full rounded-full", styles.button)}
              style={{ width: `${(plan.overall_confidence || 0.7) * 100}%` }}
            />
          </div>
          <span className={cn("text-xs", styles.subtext)}>
            {Math.round((plan.overall_confidence || 0.7) * 100)}% confidence
          </span>
        </div>
      </div>

      {/* Week Summary */}
      <div className={cn("p-3 border-b", styles.border, styles.accentBg)}>
        <div className={cn("text-sm font-medium", styles.accent)}>
          {plan.week_summary}
        </div>
      </div>

      {/* Day Selector */}
      <div className="p-2 overflow-x-auto">
        <div className="flex gap-2">
          {plan.daily_plan.map((day, index) => (
            <div key={day.date} className="w-24 shrink-0">
              <DayCard
                day={day}
                isActive={index === selectedDayIndex}
                onClick={() => setSelectedDayIndex(index)}
                styles={styles}
              />
            </div>
          ))}
        </div>
      </div>

      {/* Day Details */}
      <div className="flex-1 overflow-y-auto p-4 space-y-4">
        {currentDay && (
          <>
            {/* Coach Message */}
            <div className={cn("p-4 rounded-xl border-l-4 border-l-orange-500", styles.card, styles.border)}>
              <div className="flex items-start gap-3">
                <Sparkles className={cn("w-5 h-5 shrink-0 mt-0.5", styles.accent)} />
                <div>
                  <div className={cn("font-semibold mb-1", styles.header)}>Iron Coach Says:</div>
                  <div className={cn("text-sm", styles.header)}>{currentDay.coach_message}</div>
                </div>
              </div>
            </div>

            {/* Workout */}
            <WorkoutSection workout={currentDay.workout} styles={styles} />

            {/* Nutrition */}
            <NutritionSection nutrition={currentDay.nutrition} styles={styles} />

            {/* Sleep & Supplements */}
            <SleepSupplementsSection 
              sleep={currentDay.sleep} 
              supplements={currentDay.supplements}
              reminders={currentDay.daily_reminders}
              styles={styles} 
            />
          </>
        )}
      </div>
    </div>
  );
}

export default IronCoachPlanner;
